name: fonduer-mlflow
dependencies:
  - python=3.7
  - psycopg2
  - pip
  - pip:
    - torch==1.1.0
    - mlflow==1.4.0
    - git+https://github.com/HazyResearch/fonduer@ace413d0a687f8e9aa817389c8576d77c02baa59
