name: fonduer-mlflow
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - psycopg2
  - pytorch
  - cpuonly
  - pip
  - pip:
    - sqlalchemy<=1.3.13
    - git+https://github.com/HazyResearch/fonduer.git
