name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==1.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install mlflow==1.4.0
        sudo apt update && sudo apt install -y --no-install-recommends libpq-dev
        pip install fonduer==0.7.1
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Setup a database
      run:
        docker run --name postgres -e POSTGRES_USER=runner -e POSTGRES_DB=pob_presidents -d -p 5432:5432 postgres
    - name: Train a model
      run: |
        ./download_data.sh
        mlflow run ./ --no-conda -P conn_string=postgresql://localhost:5432/pob_presidents
